In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('../data/13_diecasting_shot_copy.csv')

In [13]:
df['비스킷두께'].info

<bound method Series.info of 0      10.0
1      11.0
2      11.0
3      11.0
4      11.0
       ...
195    19.0
196    20.0
197    27.0
198    19.0
199    15.0
Name: 비스킷두께, Length: 200, dtype: float64>

In [5]:
df['비스킷두께'] >= 16
# [False, False, False]

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199    False
Name: 비스킷두께, Length: 200, dtype: bool

In [6]:
cond=df['비스킷두께'] >= 16

In [7]:
cond.head(3).to_list()

[False, False, False]

In [8]:
cond.sum()

np.int64(74)

In [9]:
df[cond]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
67    68  DIE-B-02  215.0  1040.0   21.1   17.0  257.0   양품
108  109  DIE-A-01  264.0   594.0   36.4   18.0  363.0   양품
109  110  DIE-A-02  265.0   596.0   36.6   17.0  352.0   양품
110  111  DIE-A-02  264.0   595.0   37.0   18.0  361.0   양품
..   ...       ...    ...     ...    ...    ...    ...  ...
194  195  DIE-A-02  260.0   585.0   33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0   76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0   36.1   19.0  372.0   불량

[74 rows x 8 columns]

In [11]:
df[cond]['비스킷두께'].values

array([21., 17., 18., 17., 18., 17., 16., 16., 17., 17., 16., 17., 18.,
       19., 19., 19., 19., 18., 17., 18., 16., 19., 18., 19., 17., 17.,
       17., 16., 17., 17., 18., 17., 19., 17., 19., 19., 17., 19., 19.,
       18., 19., 19., 16., 16., 16., 18., 18., 17., 17., 19., 18., 18.,
       18., 19., 18., 18., 20., 17., 17., 17., 18., 17., 17., 17., 16.,
       18., 26., 19., 19., 19., 19., 20., 27., 19.])

In [14]:
df['비스킷두께'].isna().sum()

np.int64(14)

In [15]:
df.info

<bound method DataFrame.info of        샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]>

In [16]:
df['비스킷두께'] > 16

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199    False
Name: 비스킷두께, Length: 200, dtype: bool

In [17]:
cond.sum()

np.int64(74)

In [18]:
df['비스킷두께'] < 16

0       True
1       True
2       True
3       True
4       True
       ...
195    False
196    False
197    False
198    False
199     True
Name: 비스킷두께, Length: 200, dtype: bool

In [19]:
min=df['비스킷두께'] < 16

In [20]:
min.sum()

np.int64(112)

In [21]:
cond

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199    False
Name: 비스킷두께, Length: 200, dtype: bool

In [23]:
df[cond]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
67    68  DIE-B-02  215.0  1040.0   21.1   17.0  257.0   양품
108  109  DIE-A-01  264.0   594.0   36.4   18.0  363.0   양품
109  110  DIE-A-02  265.0   596.0   36.6   17.0  352.0   양품
110  111  DIE-A-02  264.0   595.0   37.0   18.0  361.0   양품
..   ...       ...    ...     ...    ...    ...    ...  ...
194  195  DIE-A-02  260.0   585.0   33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0   76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0   36.1   19.0  372.0   불량

[74 rows x 8 columns]

In [24]:
df[min]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[112 rows x 8 columns]

In [25]:
df[cond].value_counts

<bound method DataFrame.value_counts of        샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
67    68  DIE-B-02  215.0  1040.0   21.1   17.0  257.0   양품
108  109  DIE-A-01  264.0   594.0   36.4   18.0  363.0   양품
109  110  DIE-A-02  265.0   596.0   36.6   17.0  352.0   양품
110  111  DIE-A-02  264.0   595.0   37.0   18.0  361.0   양품
..   ...       ...    ...     ...    ...    ...    ...  ...
194  195  DIE-A-02  260.0   585.0   33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0   76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0   36.1   19.0  372.0   불량

[74 rows x 8 columns]>

In [29]:
df[cond + min]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[186 rows x 8 columns]

In [37]:
c=df['비스킷두께'].isna()

In [36]:
c.sum()

np.int64(14)

In [40]:
df[c]

       샷      설비ID  실린더압력  주조압력  사이클타임  비스킷두께  형체력 품질등급
94    95  DIE-A-01    NaN   NaN    NaN    NaN  NaN   양품
95    96  DIE-B-01    NaN   NaN    NaN    NaN  NaN   양품
96    97  DIE-B-01    NaN   NaN    NaN    NaN  NaN   양품
97    98  DIE-B-01    NaN   NaN    NaN    NaN  NaN   양품
98    99  DIE-A-01    NaN   NaN    NaN    NaN  NaN   양품
99   100  DIE-A-02    NaN   NaN    NaN    NaN  NaN   양품
100  101  DIE-A-02    NaN   NaN    NaN    NaN  NaN   양품
101  102  DIE-A-01    NaN   NaN    NaN    NaN  NaN   양품
102  103  DIE-A-01    NaN   NaN    NaN    NaN  NaN   양품
103  104  DIE-C-01    NaN   NaN    NaN    NaN  NaN   양품
104  105  DIE-A-01    NaN   NaN    NaN    NaN  NaN   양품
187  188  DIE-A-01    NaN   NaN    NaN    NaN  NaN   불량
188  189  DIE-A-01    NaN   NaN    NaN    NaN  NaN   불량
189  190  DIE-B-01    NaN   NaN    NaN    NaN  NaN   불량

In [41]:
(df['비스킷두께'] >= 16) & (df['사이클타임'] >= 25)

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199    False
Length: 200, dtype: bool

In [42]:
both=(df['비스킷두께'] >= 16) & (df['사이클타임'] >= 25)

In [43]:
df[both]

       샷      설비ID  실린더압력   주조압력  사이클타임  비스킷두께    형체력 품질등급
108  109  DIE-A-01  264.0  594.0   36.4   18.0  363.0   양품
109  110  DIE-A-02  265.0  596.0   36.6   17.0  352.0   양품
110  111  DIE-A-02  264.0  595.0   37.0   18.0  361.0   양품
111  112  DIE-B-02  265.0  595.0   36.9   17.0  355.0   양품
112  113  DIE-A-01  264.0  594.0   33.9   16.0  363.0   양품
..   ...       ...    ...    ...    ...    ...    ...  ...
194  195  DIE-A-02  260.0  585.0   33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0  594.0   76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0  595.0   36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0  255.0   36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0  595.0   36.1   19.0  372.0   불량

[72 rows x 8 columns]

In [46]:
either = (df['비스킷두께']>=16) | (df['사이클타임']>=25)

In [47]:
df[either]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0    20.7   21.0  253.0   주의
67    68  DIE-B-02  215.0  1040.0    21.1   17.0  257.0   양품
108  109  DIE-A-01  264.0   594.0    36.4   18.0  363.0   양품
109  110  DIE-A-02  265.0   596.0    36.6   17.0  352.0   양품
110  111  DIE-A-02  264.0   595.0    37.0   18.0  361.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[86 rows x 8 columns]

In [49]:
# ~ tilder

In [50]:
df[~(df['품질등급'] == '불량')]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품
..   ...       ...    ...     ...    ...    ...    ...  ...
175  176  DIE-B-02  265.0   596.0   36.0   17.0  359.0   양품
176  177  DIE-A-01  264.0   595.0   36.0   17.0  361.0   양품
177  178  DIE-B-02  264.0   595.0   36.0   17.0  355.0   양품
178  179  DIE-B-01  265.0   595.0   36.1   16.0  372.0   양품
179  180  DIE-C-01  265.0   596.0   36.2   18.0  382.0   양품

[180 rows x 8 columns]

In [51]:
~5 + 1

-5

In [52]:
5 + (~5 + 1)

0

In [53]:
df['품질등급']

0      양품
1      양품
2      양품
3      양품
4      양품
       ..
195    불량
196    불량
197    불량
198    불량
199    불량
Name: 품질등급, Length: 200, dtype: str

In [54]:
df['품질등급'] == '불량'

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199     True
Name: 품질등급, Length: 200, dtype: bool

In [55]:
df[df['품질등급'] == '불량']

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

In [56]:
df[~(df['품질등급'] == '불량')]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품
..   ...       ...    ...     ...    ...    ...    ...  ...
175  176  DIE-B-02  265.0   596.0   36.0   17.0  359.0   양품
176  177  DIE-A-01  264.0   595.0   36.0   17.0  361.0   양품
177  178  DIE-B-02  264.0   595.0   36.0   17.0  355.0   양품
178  179  DIE-B-01  265.0   595.0   36.1   16.0  372.0   양품
179  180  DIE-C-01  265.0   596.0   36.2   18.0  382.0   양품

[180 rows x 8 columns]

In [58]:
len(df[df['품질등급'] == '불량']) + len(df[~(df['품질등급'] == '불량')])

200

In [ ]:
len(df[(df['비스킷두께']>=16) & (df['사이클타임']>=25)])

72

In [71]:
df['품질등급'].isin(['주의'])

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: 품질등급, Length: 200, dtype: bool

In [73]:
df['품질등급'].isin(['주의']).value_counts

<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: 품질등급, Length: 200, dtype: bool>

In [74]:
df['품질등급'].isna().sum()

np.int64(0)

In [79]:
df['품질등급'].isin(['주의',['불량']])

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: 품질등급, Length: 200, dtype: bool

In [83]:
df[df['품질등급'].isin(['주의','불량'])]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0    20.7   21.0  253.0   주의
89    90  DIE-A-02  235.0  1137.0    22.5    7.0  255.0   주의
120  121  DIE-A-01  265.0   596.0    33.9   19.0  354.0   주의
122  123  DIE-C-01  265.0   596.0    33.7   19.0  357.0   주의
123  124  DIE-B-02  265.0   595.0    33.9   19.0  359.0   주의
124  125  DIE-A-01  265.0   595.0    33.8   19.0  355.0   주의
132  133  DIE-A-01  265.0   596.0    35.0   19.0  373.0   주의
135  136  DIE-A-02  265.0   595.0    36.0   19.0  377.0   주의
146  147  DIE-A-02  263.0   592.0   125.9   19.0  372.0   주의
148  149  DIE-B-02  265.0   596.0    36.0   19.0  377.0   주의
149  150  DIE-A-01  265.0   596.0    36.1   19.0  350.0   주의
151  152  DIE-A-01  265.0   595.0    35.9   19.0  381.0   주의
152  153  DIE-A-02  265.0   595.0    36.0   19.0  352.0   주의
154  155  DIE-A-01  265.0   595.0    35.8   19.0  363.0   주의
155  156  DIE-A-01  265.0   596.0    35.7   19.0  364.0   주의
163  164  DIE-B-02  265.0   595.0    35.8   19.0  379.0   주의
167  168  DIE-A-01  265.0   596.0    36.0   19.0  379.0   주의
170  171  DIE-B-02  265.0   596.0    36.1   20.0  370.0   주의
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

In [85]:
len(df[df['품질등급'].isin(['주의','불량'])])

38

In [93]:
df[df['비스킷두께'].between(10,16)]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[117 rows x 8 columns]

In [88]:
len(df[df['비스킷두께'].between(10,16)])

117

In [89]:
df['비스킷두께'].isna().sum()

np.int64(14)

In [90]:
len(df[~df['비스킷두께'].between(10,16)])

83

In [91]:
117 + 83

200

In [94]:
df['설비ID']

0      DIE-A-01
1      DIE-B-01
2      DIE-B-01
3      DIE-B-02
4      DIE-A-01
         ...
195    DIE-A-01
196    DIE-A-01
197    DIE-A-01
198    DIE-B-02
199    DIE-A-01
Name: 설비ID, Length: 200, dtype: str

In [96]:
df['설비ID'].str.contains('A')

0       True
1      False
2      False
3      False
4       True
       ...
195     True
196     True
197     True
198    False
199     True
Name: 설비ID, Length: 200, dtype: bool

In [97]:
df[df['설비ID'].str.contains('A')]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
5      6  DIE-A-01  217.0  1052.0    20.6   11.0  257.0   양품
6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품
7      8  DIE-A-01  215.0  1038.0    20.9   11.0  258.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[111 rows x 8 columns]

In [98]:
'DIE-A-01'.split('-')[1]

'A'

In [101]:
df['설비ID'].str.split('-').str[1]

0      A
1      B
2      B
3      B
4      A
      ..
195    A
196    A
197    A
198    B
199    A
Name: 설비ID, Length: 200, dtype: object

In [102]:
df['설비ID'].str.split('-').str[2]

0      01
1      01
2      01
3      02
4      01
       ..
195    01
196    01
197    01
198    02
199    01
Name: 설비ID, Length: 200, dtype: object

In [103]:
df['설비ID'].values

<ArrowStringArray>
['DIE-A-01', 'DIE-B-01', 'DIE-B-01', 'DIE-B-02', 'DIE-A-01', 'DIE-A-01',
 'DIE-A-01', 'DIE-A-01', 'DIE-B-02', 'DIE-A-01',
 ...
 'DIE-B-02', 'DIE-B-01', 'DIE-A-02', 'DIE-C-01', 'DIE-A-02', 'DIE-A-01',
 'DIE-A-01', 'DIE-A-01', 'DIE-B-02', 'DIE-A-01']
Length: 200, dtype: str

In [104]:
df['설비ID'].head(1).tolist()

['DIE-A-01']

In [105]:
라인  = df['설비ID'].str.split('-').str[1]

In [106]:
호기  = df['설비ID'].str.split('-').str[2]

In [107]:
print((라인 =='A').sum(), (라인 =='B').sum(), (라인 =='C').sum())

111 74 15

In [108]:
print((호기 =='01').sum(), (호기 =='02').sum())

114 86

In [109]:
print(df['설비ID'].str.replace('DIE-', '', regex=False).head(1).tolist())

['A-01']

In [110]:
df['설비ID'].str.replace('DIE-', '')

0      A-01
1      B-01
2      B-01
3      B-02
4      A-01
       ...
195    A-01
196    A-01
197    A-01
198    B-02
199    A-01
Name: 설비ID, Length: 200, dtype: str

In [111]:
df = pd.read_csv('../data/13_diecasting_shot_copy.csv')

In [112]:
df['품질등급'].isin(['주의','불량'])

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199     True
Name: 품질등급, Length: 200, dtype: bool

In [113]:
df[df['품질등급'].isin(['주의','불량'])]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0    20.7   21.0  253.0   주의
89    90  DIE-A-02  235.0  1137.0    22.5    7.0  255.0   주의
120  121  DIE-A-01  265.0   596.0    33.9   19.0  354.0   주의
122  123  DIE-C-01  265.0   596.0    33.7   19.0  357.0   주의
123  124  DIE-B-02  265.0   595.0    33.9   19.0  359.0   주의
124  125  DIE-A-01  265.0   595.0    33.8   19.0  355.0   주의
132  133  DIE-A-01  265.0   596.0    35.0   19.0  373.0   주의
135  136  DIE-A-02  265.0   595.0    36.0   19.0  377.0   주의
146  147  DIE-A-02  263.0   592.0   125.9   19.0  372.0   주의
148  149  DIE-B-02  265.0   596.0    36.0   19.0  377.0   주의
149  150  DIE-A-01  265.0   596.0    36.1   19.0  350.0   주의
151  152  DIE-A-01  265.0   595.0    35.9   19.0  381.0   주의
152  153  DIE-A-02  265.0   595.0    36.0   19.0  352.0   주의
154  155  DIE-A-01  265.0   595.0    35.8   19.0  363.0   주의
155  156  DIE-A-01  265.0   596.0    35.7   19.0  364.0   주의
163  164  DIE-B-02  265.0   595.0    35.8   19.0  379.0   주의
167  168  DIE-A-01  265.0   596.0    36.0   19.0  379.0   주의
170  171  DIE-B-02  265.0   596.0    36.1   20.0  370.0   주의
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

In [117]:
aline=df[df['품질등급'].isin(['주의','불량'])]

In [115]:
df['비스킷두께'].between(10,16)

0       True
1       True
2       True
3       True
4       True
       ...
195    False
196    False
197    False
198    False
199     True
Name: 비스킷두께, Length: 200, dtype: bool

In [116]:
bline=df[df['비스킷두께'].between(10,16)]

In [118]:
len(aline)

38

In [119]:
len(bline)

117

In [120]:
df[df['설비ID'].str.contains('A')]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
5      6  DIE-A-01  217.0  1052.0    20.6   11.0  257.0   양품
6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품
7      8  DIE-A-01  215.0  1038.0    20.9   11.0  258.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[111 rows x 8 columns]

In [121]:
Ashot=df[df['설비ID'].str.contains('A')]

In [122]:
len(Ashot)

111

In [124]:
df[df['설비ID'] == 'DIE-A-01']

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
5      6  DIE-A-01  217.0  1052.0    20.6   11.0  257.0   양품
6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품
7      8  DIE-A-01  215.0  1038.0    20.9   11.0  258.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[63 rows x 8 columns]

In [125]:
Ahogi=df[df['설비ID'] == 'DIE-A-01']

In [126]:
len(Ahogi)

63

In [127]:
df.sort_values(['품질등급','사이클타임'])

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
183  184  DIE-B-01  216.0  1044.0   21.2   11.0  259.0   불량
182  183  DIE-A-02  215.0  1041.0   21.3    4.0  258.0   불량
184  185  DIE-B-01  219.0  1058.0   21.3    2.0  255.0   불량
185  186  DIE-B-02  218.0  1054.0   21.4    2.0  253.0   불량
186  187  DIE-C-01  108.0   524.0   22.9   14.0  247.0   불량
..   ...       ...    ...     ...    ...    ...    ...  ...
152  153  DIE-A-02  265.0   595.0   36.0   19.0  352.0   주의
167  168  DIE-A-01  265.0   596.0   36.0   19.0  379.0   주의
149  150  DIE-A-01  265.0   596.0   36.1   19.0  350.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
146  147  DIE-A-02  263.0   592.0  125.9   19.0  372.0   주의

[200 rows x 8 columns]

In [ ]:
df.sort_values(['품질등급','사이클타임'], ascending=[True,False])

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
..   ...       ...    ...     ...     ...    ...    ...  ...
123  124  DIE-B-02  265.0   595.0    33.9   19.0  359.0   주의
124  125  DIE-A-01  265.0   595.0    33.8   19.0  355.0   주의
122  123  DIE-C-01  265.0   596.0    33.7   19.0  357.0   주의
89    90  DIE-A-02  235.0  1137.0    22.5    7.0  255.0   주의
42    43  DIE-A-01  215.0  1040.0    20.7   21.0  253.0   주의

[200 rows x 8 columns]

In [129]:
df.nlargest(5,'비스킷두께')

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량

In [130]:
df.sort_values(['비스킷두께'], ascending=False).head(5)

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('../data/13_diecasting_shot_copy.csv')

In [10]:
df.sort_values(['품질등급','사이클타임'], ascending=[True,False]).head(5)

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량

In [12]:
df[df['품질등급'] == '불량']

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

In [13]:
불량=df[df['품질등급'] == '불량'].copy()

In [15]:
불량.head()

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
180  181  DIE-B-01  108.0   522.0  652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0   93.1   12.0  247.0   불량
182  183  DIE-A-02  215.0  1041.0   21.3    4.0  258.0   불량
183  184  DIE-B-01  216.0  1044.0   21.2   11.0  259.0   불량
184  185  DIE-B-01  219.0  1058.0   21.3    2.0  255.0   불량

In [16]:
불량['위험등급']

KeyError: '위험등급'

In [ ]:
불량['위험등급'] = '높음'

In [18]:
불량

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급 위험등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량   높음
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량   높음
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량   높음
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량   높음
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량   높음
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량   높음
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량   높음
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량   높음
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량   높음
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량   높음
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량   높음
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량   높음
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량   높음
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량   높음
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량   높음
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량   높음
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량   높음
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량   높음
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량   높음
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량   높음

In [22]:
불량['위험등급'] = 'high'

In [23]:
불량

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급  위험등급 High
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량  high   높음
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량  high   높음
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량  high   높음
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량  high   높음
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량  high   높음
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량  high   높음
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량  high   높음
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량  high   높음
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량  high   높음
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량  high   높음
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량  high   높음
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량  high   높음
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량  high   높음
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량  high   높음
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량  high   높음
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량  high   높음
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량  high   높음
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량  high   높음
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량  high   높음
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량  high   높음

In [27]:
불량

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급  위험등급 High
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량  high   높음
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량  high   높음
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량  high   높음
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량  high   높음
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량  high   높음
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량  high   높음
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량  high   높음
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량  high   높음
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량  high   높음
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량  high   높음
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량  high   높음
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량  high   높음
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량  high   높음
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량  high   높음
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량  high   높음
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량  high   높음
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량  high   높음
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량  high   높음
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량  high   높음
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량  high   높음

In [26]:
불량

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급  위험등급 High
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량  high   높음
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량  high   높음
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량  high   높음
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량  high   높음
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량  high   높음
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량  high   높음
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량  high   높음
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량  high   높음
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량  high   높음
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량  high   높음
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량  high   높음
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량  high   높음
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량  high   높음
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량  high   높음
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량  high   높음
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량  high   높음
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량  high   높음
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량  high   높음
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량  high   높음
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량  high   높음

In [28]:
불량 = 불량.drop(columns=['High'])

In [29]:
불량

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급  위험등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량  high
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량  high
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량  high
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량  high
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량  high
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량  high
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량  high
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량  high
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량  high
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량  high
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량  high
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량  high
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량  high
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량  high
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량  high
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량  high
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량  high
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량  high
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량  high
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량  high

In [30]:
불량.shape

(20, 9)

In [31]:
판정=df.copy()

In [33]:
판정['설비ID']

0      DIE-A-01
1      DIE-B-01
2      DIE-B-01
3      DIE-B-02
4      DIE-A-01
         ...
195    DIE-A-01
196    DIE-A-01
197    DIE-A-01
198    DIE-B-02
199    DIE-A-01
Name: 설비ID, Length: 200, dtype: str

In [34]:
판정['설비ID'].str.split('-')

0      [DIE, A, 01]
1      [DIE, B, 01]
2      [DIE, B, 01]
3      [DIE, B, 02]
4      [DIE, A, 01]
           ...
195    [DIE, A, 01]
196    [DIE, A, 01]
197    [DIE, A, 01]
198    [DIE, B, 02]
199    [DIE, A, 01]
Name: 설비ID, Length: 200, dtype: object

In [35]:
판정['설비ID'].str.split('-').str

In [36]:
판정['설비ID'].str.split('-').str[1]

0      A
1      B
2      B
3      B
4      A
      ..
195    A
196    A
197    A
198    B
199    A
Name: 설비ID, Length: 200, dtype: object

In [37]:
판정['라인'] = 판정['설비ID'].str.split('-').str[1]

In [38]:
판정

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급 라인
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품  A
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품  B
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품  B
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품  B
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품  A
..   ...       ...    ...     ...     ...    ...    ...  ... ..
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량  A
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량  A
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량  A
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량  B
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량  A

[200 rows x 9 columns]

In [40]:
판정['비스킷두께'] >= 16

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199    False
Name: 비스킷두께, Length: 200, dtype: bool

In [41]:
판정.loc[판정['비스킷두께'] >= 16,]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급 라인
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의  A
67    68  DIE-B-02  215.0  1040.0   21.1   17.0  257.0   양품  B
108  109  DIE-A-01  264.0   594.0   36.4   18.0  363.0   양품  A
109  110  DIE-A-02  265.0   596.0   36.6   17.0  352.0   양품  A
110  111  DIE-A-02  264.0   595.0   37.0   18.0  361.0   양품  A
..   ...       ...    ...     ...    ...    ...    ...  ... ..
194  195  DIE-A-02  260.0   585.0   33.9   19.0  348.0   불량  A
195  196  DIE-A-01  264.0   594.0   76.3   19.0  381.0   불량  A
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량  A
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량  A
198  199  DIE-B-02  264.0   595.0   36.1   19.0  372.0   불량  B

[74 rows x 9 columns]

In [42]:
판정.loc[판정['비스킷두께'] >= 16,'품질등급']

42     주의
67     양품
108    양품
109    양품
110    양품
       ..
194    불량
195    불량
196    불량
197    불량
198    불량
Name: 품질등급, Length: 74, dtype: str

In [44]:
판정.loc[판정['비스킷두께'] >= 16,'두께판정'] = "두꺼움"

In [45]:
판정

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급 라인 두께판정
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품  A  NaN
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품  B  NaN
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품  B  NaN
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품  B  NaN
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품  A  NaN
..   ...       ...    ...     ...     ...    ...    ...  ... ..  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량  A  두꺼움
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량  A  두꺼움
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량  A  두꺼움
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량  B  두꺼움
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량  A  NaN

[200 rows x 10 columns]

In [46]:
판정['두께판정'].notna().sum()

np.int64(74)

In [47]:
판정['형체력'] - 250

0        8.0
1        7.0
2        4.0
3        3.0
4        4.0
       ...
195    131.0
196    105.0
197    104.0
198    122.0
199    -13.0
Name: 형체력, Length: 200, dtype: float64

In [48]:
판정['여유형체력'] = 판정['형체력'] - 250

In [49]:
판정

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급 라인 두께판정  여유형체력
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품  A  NaN    8.0
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품  B  NaN    7.0
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품  B  NaN    4.0
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품  B  NaN    3.0
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품  A  NaN    4.0
..   ...       ...    ...     ...     ...    ...    ...  ... ..  ...    ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량  A  두꺼움  131.0
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량  A  두꺼움  105.0
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량  A  두꺼움  104.0
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량  B  두꺼움  122.0
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량  A  NaN  -13.0

[200 rows x 11 columns]

In [58]:
df[~(df['품질등급'] == '양품') & (df['비스킷두께'] >= 16)]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
120  121  DIE-A-01  265.0   596.0   33.9   19.0  354.0   주의
122  123  DIE-C-01  265.0   596.0   33.7   19.0  357.0   주의
123  124  DIE-B-02  265.0   595.0   33.9   19.0  359.0   주의
124  125  DIE-A-01  265.0   595.0   33.8   19.0  355.0   주의
132  133  DIE-A-01  265.0   596.0   35.0   19.0  373.0   주의
135  136  DIE-A-02  265.0   595.0   36.0   19.0  377.0   주의
146  147  DIE-A-02  263.0   592.0  125.9   19.0  372.0   주의
148  149  DIE-B-02  265.0   596.0   36.0   19.0  377.0   주의
149  150  DIE-A-01  265.0   596.0   36.1   19.0  350.0   주의
151  152  DIE-A-01  265.0   595.0   35.9   19.0  381.0   주의
152  153  DIE-A-02  265.0   595.0   36.0   19.0  352.0   주의
154  155  DIE-A-01  265.0   595.0   35.8   19.0  363.0   주의
155  156  DIE-A-01  265.0   596.0   35.7   19.0  364.0   주의
163  164  DIE-B-02  265.0   595.0   35.8   19.0  379.0   주의
167  168  DIE-A-01  265.0   596.0   36.0   19.0  379.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
192  193  DIE-A-02  264.0   594.0   36.9   19.0  355.0   불량
193  194  DIE-C-01  113.0   255.0   34.4   19.0  370.0   불량
194  195  DIE-A-02  260.0   585.0   33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0   76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0   36.1   19.0  372.0   불량

In [59]:
불량 = df[~(df['품질등급'] == '양품') & (df['비스킷두께'] >= 16)]

In [69]:
len(불량)

25

In [61]:
순서 = 불량.sort_values('비스킷두께',ascending=False)

In [67]:
걸러진것 = 순서[['설비ID','비스킷두께','품질등급']]

In [68]:
걸러진것.head(5)

         설비ID  비스킷두께 품질등급
197  DIE-A-01   27.0   불량
191  DIE-B-01   26.0   불량
42   DIE-A-01   21.0   주의
196  DIE-A-01   20.0   불량
170  DIE-B-02   20.0   주의